# Justfile

# プロジェクトルートを取得し、ビルドディレクトリを作り直す
default:
    just build

# プロジェクトルートを取得し、ビルドディレクトリを作り直す
build:
    rm -rf ./build
    cmake -S . -B ./build -G Ninja -DENABLE_OPENMP=ON
    cmake --build ./build

# 実行ファイルを走らせる
run:
    ./build/main

# ビルドしてから実行する
all:
    just build
    just run


#サーバーを実行し、Web ブラウザや curl などで http://localhost:8080/cog?path=/actual/path/to/your.tif のような URL にアクセス
# （/actual/path/to/your.tif は、コード内の base_dir からの相対パスまたは設定に応じたパスに置き換えてください）。
# http://localhost:8080/cog?path=./data/test.tif
# http://localhost:8080/cog?path=./test.tif